//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchProfiles.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://craftjack.com/", ConfigurationName="ServiceReference1.matchesSoap")]
    public interface matchesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://craftjack.com/GetLeadIdFromHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long GetLeadIdFromHash(string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://craftjack.com/GetLeadDetailFromHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetLeadDetailFromHash(string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://craftjack.com/GetMatches", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlElement GetMatches(string hash, int contractorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://craftjack.com/AddReview", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddReview(long contractorId, string hash, bool hired, string comments, int rating, int responsiveness, int quality, int timeliness, int flexibility, int professionalism, int price, int reliability, int manners, int speed, int honesty);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface matchesSoapChannel : MatchProfiles.ServiceReference1.matchesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class matchesSoapClient : System.ServiceModel.ClientBase<MatchProfiles.ServiceReference1.matchesSoap>, MatchProfiles.ServiceReference1.matchesSoap {
        
        public matchesSoapClient() {
        }
        
        public matchesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public matchesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public matchesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public matchesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long GetLeadIdFromHash(string hash) {
            return base.Channel.GetLeadIdFromHash(hash);
        }
        
        public System.Xml.XmlElement GetLeadDetailFromHash(string hash) {
            return base.Channel.GetLeadDetailFromHash(hash);
        }
        
        public System.Xml.XmlElement GetMatches(string hash, int contractorId) {
            return base.Channel.GetMatches(hash, contractorId);
        }
        
        public string AddReview(long contractorId, string hash, bool hired, string comments, int rating, int responsiveness, int quality, int timeliness, int flexibility, int professionalism, int price, int reliability, int manners, int speed, int honesty) {
            return base.Channel.AddReview(contractorId, hash, hired, comments, rating, responsiveness, quality, timeliness, flexibility, professionalism, price, reliability, manners, speed, honesty);
        }
    }
}
